[tool.poetry]
name = "triangle"
version = "0.1.0"
description = ""
authors = ["easai <aksarih@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
